---
- name: Set up
  hosts: droplets
  gather_facts: no
  tasks:
  - name: Wait 300 seconds, but only start checking after 15 seconds 
    ansible.builtin.wait_for_connection:
      delay: 15
      timeout: 100
  - name: Update repositories cache and install "unzip" package
    ansible.builtin.apt:
      name: unzip
      update_cache: yes
    register: result
    until: result is succeeded
    retries: 5
    delay: 10
  - name: Copy scripts
    ansible.builtin.copy:
      src: ../scripts/
      dest: scripts/
      mode: preserve
  - name: Copy wordlists
    ansible.builtin.copy:
      src: ../wordlists/
      dest: wordlists/
      mode: preserve
  - name: Create a directory if it does not exist ('output')
    ansible.builtin.file:
      path: output
      state: directory
  - name: Change file permissions to be executable
    ansible.builtin.file:
      path: scripts/
      mode: '0755'
      recurse: yes
  - name: Install seclists
    ansible.builtin.command: snap install seclists
  - name: Install feroxbuster
    ansible.builtin.shell: curl -sL https://raw.githubusercontent.com/epi052/feroxbuster/main/install-nix.sh | bash 